"""Constants for mywatertornto tests."""

from custom_components.mywatertoronto.const import (
    CONF_ACCOUNT_NUMBER,
    CONF_CLIENT_NUMBER,
    CONF_LAST_NAME,
    CONF_LAST_PAYMENT_METHOD,
    CONF_POSTAL_CODE,
)

TEST_TITLE = "123 Main St Water Meter"
TEST_ACCOUNT_NUMBER = "000123456"
TEST_CLIENT_NUMBER = "001234567-89"
TEST_LAST_NAME = "Lastname"
TEST_LAST_PAYMENT_METHOD = "4"
TEST_POSTAL_CODE = "A1A 1A1"
TEST_UNIQUE_ID = f"{TEST_ACCOUNT_NUMBER}-{TEST_CLIENT_NUMBER}"

# Mock config data to be used across multiple tests
MOCK_CONFIG = {
    CONF_ACCOUNT_NUMBER: TEST_ACCOUNT_NUMBER,
    CONF_CLIENT_NUMBER: TEST_CLIENT_NUMBER,
    CONF_LAST_NAME: TEST_LAST_NAME,
    CONF_LAST_PAYMENT_METHOD: TEST_LAST_PAYMENT_METHOD,
    CONF_POSTAL_CODE: TEST_POSTAL_CODE,
}
